### ISSUE TITLE
SSDの検出結果からBoundingBoxをだす

### ISSUE THREAD

**Issue by Kanazawanaoaki** [Kanazawanaoaki/cook_eyes#6]
https://github.com/jsk-ros-pkg/jsk_recognition/pull/2511 を使ってRectArray -> ClusterPointIndicesの変換をしてその出力をhttps://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/sample/tabletop_object_detector.launch のeuclidean clusteringの部分を置き換える。  

https://github.com/Kanazawanaoaki/cook_eyes/commit/aaf54ab3d04aebd637091a0477123d7cee534e1f#diff-363e68923b115984009fddf2cdcfe078 を作って試して見ましたが、上手くバウンディングボックスが出ませんでした。  
![Screenshot from 2020-06-10 14-31-38](https://user-images.githubusercontent.com/38127823/84230555-2caf9480-ab27-11ea-9272-97295b5cbc41.png)

実行しているのは、  
```
roslaunch kitchen_recognition tabletop_test_ssd_vegs.launch
```
```
roslaunch kitchen_recognition depth2ptcloud.launch gui:=false
```
https://github.com/Kanazawanaoaki/cook_eyes_coral/tree/master/curry_detector_ros のCoral TPUのSSDのlaunchを走らせる
```
roslaunch curry_detector_ros edgetpu_vegs_detector.launch INPUT_IMAGE:=/camera/rgb/image_raw
```
https://drive.google.com/file/d/1PVW_1rERg6YojUP5fFfc3UdM2Mx2U2s3/view?usp=sharing のrosbagを再生する。  
```
rosbag play vegs_test.bag -l
```

**Comment by Kanazawanaoaki** [comment]
```
 rostopic echo /camera/rgb/image_raw | grep header -A 10
header: 
  seq: 1242
  stamp: 
    secs: 1591455782
    nsecs:  22477142
  frame_id: "camera_rgb_optical_frame"
height: 480
width: 640
encoding: "rgb8"
is_bigendian: 0
step: 1920
```
なので、パラメータもあっているはずだと思いますし、
(https://github.com/jsk-ros-pkg/jsk_recognition/blob/master/jsk_pcl_ros/sample/tabletop_object_detector.launch )を使った時に出てくる`ClusterPointIndices`と値を比べてみても同じ部分を出している気もします。  
https://gist.github.com/Kanazawanaoaki/39b62a6fd89d1994e032e8cd67bb393c
![Screenshot from 2020-06-08 16-38-11](https://user-images.githubusercontent.com/38127823/84231480-3934ec80-ab29-11ea-838c-1fbd5f5e306e.png)
